base: core18
name: kubectx
version: '0.9.0'
summary: Faster way to switch between clusters and namespaces in kubectl.
description: |
  This snap provides both kubectx and kubens tools, which allow fast switching between Kubernetes clusters and namespaces.
grade: stable
confinement: classic

apps:
  kubectx:
    command: kubectx
  kubens:
    command: kubens


architectures:
  - build-on: amd64


parts:
  kubectx:
    plugin: dump
    source:
      - on amd64: https://github.com/ahmetb/kubectx/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/kubectx_v${SNAPCRAFT_PROJECT_VERSION}_linux_x86_64.tar.gz
    stage:
      - kubectx
  kubens:
    plugin: dump
    source:
      - on amd64: https://github.com/ahmetb/kubectx/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/kubens_v${SNAPCRAFT_PROJECT_VERSION}_linux_x86_64.tar.gz
    stage:
      - kubens

