base: core18
name: kubectx
version: '0.9.0'
summary: Faster way to switch between clusters and namespaces in kubectl.
description: |
  This snap provides both kubectx and kubens tools, which allow fast switching between Kubernetes clusters and namespaces. (Bash version)
grade: stable
confinement: classic

apps:
  kubectx:
    command: kubectx
    completer: completion/kubectx.bash
  kubens:
    command: kubens
    completer: completion/kubens.bash

architectures:
  - build-on: amd64

parts:
  kubectx:
    plugin: dump
    source: https://github.com/ahmetb/kubectx/archive/v${SNAPCRAFT_PROJECT_VERSION}.tar.gz
    organize:
      "/kubectx-${SNAPCRAFT_PROJECT_VERSION}/completion/*.bash" : completion/
      kubectx : usr/bin/kubectx
      kubens : usr/bin/kubens
    build-packages: [sed]
    stage:
      - usr/bin/kubectx
      - usr/bin/kubens
      - completion/*.bash
    override-build: |
      snapcraftctl build
      sed -i 's/kubens kns/kubectx.kubens/' $SNAPCRAFT_PART_INSTALL/completion/kubens.bash
